#spring:
#  mail:
#    username: 2814964382@qq.com
#    password: ${MAIL_PASSWORD}
#    host: smtp.qq.com
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      logic-delete-field: delFlag
#      id-type: auto
